# Values for Personal Cluster Deployment
# Usage: helm upgrade --install geosnappro deploy/charts/geosnappro -f deploy/charts/geosnappro/values-personal.yaml

global:
  imagePullSecrets:
    - name: ghcr-creds-regcred

frontend:
  ingress:
    enabled: true
    className: "nginx"
    annotations:
      cert-manager.io/issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
    hosts:
      - host: geosnappro.araec.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: geosnappro-araec-com-tls
        hosts:
          - geosnappro.araec.com

  mediaVolume:
    storageClass: "local-path"

  image:
    repository: ghcr.io/davidjameshowell/frontend

screenshotApi:
  image:
    repository: ghcr.io/davidjameshowell/screenshot-api

gluetunApi:
  image:
    repository: ghcr.io/davidjameshowell/gluetun-k8s-api
