# Values for Personal Cluster Deployment
# Usage: helm upgrade --install geosnappro deploy/charts/geosnappro -f deploy/charts/geosnappro/values-personal.yaml

global:
  imagePullSecrets:
    - name: ghcr-creds-regcred

frontend:
  ingress:
    enabled: true
    className: "nginx"
    annotations:
      cert-manager.io/issuer: letsencrypt-prod
    hosts:
      - host: geosnappro.araec.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: geosnappro-araec-com-tls
        hosts:
          - geosnappro.araec.com
