{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "geosnappro.frontend.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "geosnappro.frontend.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.frontend.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}

