{{- if and .Values.screenshotApi.enabled .Values.screenshotApi.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "geosnappro.screenshotApi.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "geosnappro.screenshotApi.labels" . | nindent 4 }}
  {{- if .Values.screenshotApi.serviceAccount.annotations }}
  annotations:
    {{- toYaml .Values.screenshotApi.serviceAccount.annotations | nindent 4 }}
  {{- end }}
{{- if .Values.global.imagePullSecrets }}
imagePullSecrets:
  {{- range .Values.global.imagePullSecrets }}
  - name: {{ . }}
  {{- end }}
{{- end }}
{{- end }}

