{{- if and .Values.gluetunApi.enabled .Values.gluetunApi.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "geosnappro.gluetunApi.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "geosnappro.gluetunApi.labels" . | nindent 4 }}
{{- end }}

