{{- if .Values.gluetunApi.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.gluetunApi.wireguardSecret.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "geosnappro.gluetunApi.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.gluetunApi.wireguardSecret.privateKeyKey }}: {{ .Values.gluetunApi.wireguard.privateKey | quote }}
  {{ .Values.gluetunApi.wireguardSecret.addressesKey }}: {{ .Values.gluetunApi.wireguard.addresses | quote }}
{{- end }}

