{{- if .Values.gluetunApi.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "geosnappro.gluetunApi.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "geosnappro.gluetunApi.labels" . | nindent 4 }}
spec:
  type: {{ .Values.gluetunApi.service.type }}
  selector:
    {{- include "geosnappro.gluetunApi.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.gluetunApi.service.port }}
      targetPort: http
      protocol: TCP
{{- end }}

